buildscript {
    ext {
        kotlin_version = '1.8.22' 
    }
    repositories {
        google()
        mavenCentral() 
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
}

group 'io.github.edufolly.flutterbluetoothserial'
version '1.0-SNAPSHOT'

android {
    namespace = 'com.cleverton.flutter_bluetooth_serial'
    compileSdkVersion 35 

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 35
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_11
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    buildToolsVersion '33.0.0'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
